package com.huayi.ljj.springcloud.dao;

import com.huayi.ljj.springcloud.model.TblManuFacturerPara;
import com.huayi.ljj.springcloud.model.TblManuFacturerParaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblManuFacturerParaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int countByExample(TblManuFacturerParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int deleteByExample(TblManuFacturerParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String manufacturerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int insert(TblManuFacturerPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int insertSelective(TblManuFacturerPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    List<TblManuFacturerPara> selectByExample(TblManuFacturerParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    TblManuFacturerPara selectByPrimaryKey(String manufacturerCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblManuFacturerPara record, @Param("example") TblManuFacturerParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblManuFacturerPara record, @Param("example") TblManuFacturerParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblManuFacturerPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblManuFacturerPara record);
}