package com.huayi.ljj.springcloud.dao;

import com.huayi.ljj.springcloud.model.TblOrderRecordOut;
import com.huayi.ljj.springcloud.model.TblOrderRecordOutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblOrderRecordOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int countByExample(TblOrderRecordOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int deleteByExample(TblOrderRecordOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int insert(TblOrderRecordOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int insertSelective(TblOrderRecordOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    List<TblOrderRecordOut> selectByExample(TblOrderRecordOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    TblOrderRecordOut selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblOrderRecordOut record, @Param("example") TblOrderRecordOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblOrderRecordOut record, @Param("example") TblOrderRecordOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblOrderRecordOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_out
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblOrderRecordOut record);
}