package com.huayi.ljj.springcloud.dao;

import com.huayi.ljj.springcloud.model.TblOrderRecordIn;
import com.huayi.ljj.springcloud.model.TblOrderRecordInExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblOrderRecordInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int countByExample(TblOrderRecordInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int deleteByExample(TblOrderRecordInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int insert(TblOrderRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int insertSelective(TblOrderRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    List<TblOrderRecordIn> selectByExample(TblOrderRecordInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    TblOrderRecordIn selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblOrderRecordIn record, @Param("example") TblOrderRecordInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblOrderRecordIn record, @Param("example") TblOrderRecordInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblOrderRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblOrderRecordIn record);
}