package com.huayi.ljj.springcloud.dao;

import com.huayi.ljj.springcloud.model.TblProdNamePara;
import com.huayi.ljj.springcloud.model.TblProdNameParaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblProdNameParaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int countByExample(TblProdNameParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int deleteByExample(TblProdNameParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int insert(TblProdNamePara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int insertSelective(TblProdNamePara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    List<TblProdNamePara> selectByExample(TblProdNameParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    TblProdNamePara selectByPrimaryKey(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblProdNamePara record, @Param("example") TblProdNameParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblProdNamePara record, @Param("example") TblProdNameParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblProdNamePara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblProdNamePara record);
}