package com.huayi.ljj.springcloud.dao;

import com.huayi.ljj.springcloud.model.TblProdInventory;
import com.huayi.ljj.springcloud.model.TblProdInventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblProdInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    int countByExample(TblProdInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    int deleteByExample(TblProdInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    int insert(TblProdInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    int insertSelective(TblProdInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    List<TblProdInventory> selectByExample(TblProdInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblProdInventory record, @Param("example") TblProdInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblProdInventory record, @Param("example") TblProdInventoryExample example);
}