package com.huayi.ljj.springcloud.dao;

import com.huayi.ljj.springcloud.model.TblTransLog;
import com.huayi.ljj.springcloud.model.TblTransLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblTransLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int countByExample(TblTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int deleteByExample(TblTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int insert(TblTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int insertSelective(TblTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    List<TblTransLog> selectByExample(TblTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    TblTransLog selectByPrimaryKey(String transNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblTransLog record, @Param("example") TblTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblTransLog record, @Param("example") TblTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblTransLog record);
}