package com.huayi.ljj.springcloud.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TblManuFacturerPara implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.MANUFACTURER_CODE
     *
     * @mbggenerated
     */
    private String manufacturerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.MANUFACTURER_NM
     *
     * @mbggenerated
     */
    private String manufacturerNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.MANUFACTURER_TEL
     *
     * @mbggenerated
     */
    private String manufacturerTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.TRANSPORTATION_EXPENSE
     *
     * @mbggenerated
     */
    private BigDecimal transportationExpense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.UPDATE_DT
     *
     * @mbggenerated
     */
    private String updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.TRANS_DT
     *
     * @mbggenerated
     */
    private String transDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.TRANS_TM
     *
     * @mbggenerated
     */
    private String transTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.TRANS_CD
     *
     * @mbggenerated
     */
    private String transCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD1
     *
     * @mbggenerated
     */
    private String extfld1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD2
     *
     * @mbggenerated
     */
    private String extfld2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD3
     *
     * @mbggenerated
     */
    private String extfld3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD4
     *
     * @mbggenerated
     */
    private String extfld4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD5
     *
     * @mbggenerated
     */
    private String extfld5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD6
     *
     * @mbggenerated
     */
    private String extfld6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD7
     *
     * @mbggenerated
     */
    private String extfld7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD8
     *
     * @mbggenerated
     */
    private String extfld8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_manufacturer_para.EXTFLD9
     *
     * @mbggenerated
     */
    private String extfld9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.MANUFACTURER_CODE
     *
     * @return the value of tbl_manufacturer_para.MANUFACTURER_CODE
     *
     * @mbggenerated
     */
    public String getManufacturerCode() {
        return manufacturerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.MANUFACTURER_CODE
     *
     * @param manufacturerCode the value for tbl_manufacturer_para.MANUFACTURER_CODE
     *
     * @mbggenerated
     */
    public void setManufacturerCode(String manufacturerCode) {
        this.manufacturerCode = manufacturerCode == null ? null : manufacturerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.MANUFACTURER_NM
     *
     * @return the value of tbl_manufacturer_para.MANUFACTURER_NM
     *
     * @mbggenerated
     */
    public String getManufacturerNm() {
        return manufacturerNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.MANUFACTURER_NM
     *
     * @param manufacturerNm the value for tbl_manufacturer_para.MANUFACTURER_NM
     *
     * @mbggenerated
     */
    public void setManufacturerNm(String manufacturerNm) {
        this.manufacturerNm = manufacturerNm == null ? null : manufacturerNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.MANUFACTURER_TEL
     *
     * @return the value of tbl_manufacturer_para.MANUFACTURER_TEL
     *
     * @mbggenerated
     */
    public String getManufacturerTel() {
        return manufacturerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.MANUFACTURER_TEL
     *
     * @param manufacturerTel the value for tbl_manufacturer_para.MANUFACTURER_TEL
     *
     * @mbggenerated
     */
    public void setManufacturerTel(String manufacturerTel) {
        this.manufacturerTel = manufacturerTel == null ? null : manufacturerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.TRANSPORTATION_EXPENSE
     *
     * @return the value of tbl_manufacturer_para.TRANSPORTATION_EXPENSE
     *
     * @mbggenerated
     */
    public BigDecimal getTransportationExpense() {
        return transportationExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.TRANSPORTATION_EXPENSE
     *
     * @param transportationExpense the value for tbl_manufacturer_para.TRANSPORTATION_EXPENSE
     *
     * @mbggenerated
     */
    public void setTransportationExpense(BigDecimal transportationExpense) {
        this.transportationExpense = transportationExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.UPDATE_DT
     *
     * @return the value of tbl_manufacturer_para.UPDATE_DT
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.UPDATE_DT
     *
     * @param updateDt the value for tbl_manufacturer_para.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.TRANS_DT
     *
     * @return the value of tbl_manufacturer_para.TRANS_DT
     *
     * @mbggenerated
     */
    public String getTransDt() {
        return transDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.TRANS_DT
     *
     * @param transDt the value for tbl_manufacturer_para.TRANS_DT
     *
     * @mbggenerated
     */
    public void setTransDt(String transDt) {
        this.transDt = transDt == null ? null : transDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.TRANS_TM
     *
     * @return the value of tbl_manufacturer_para.TRANS_TM
     *
     * @mbggenerated
     */
    public String getTransTm() {
        return transTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.TRANS_TM
     *
     * @param transTm the value for tbl_manufacturer_para.TRANS_TM
     *
     * @mbggenerated
     */
    public void setTransTm(String transTm) {
        this.transTm = transTm == null ? null : transTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.VERSION
     *
     * @return the value of tbl_manufacturer_para.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.VERSION
     *
     * @param version the value for tbl_manufacturer_para.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.TRANS_CD
     *
     * @return the value of tbl_manufacturer_para.TRANS_CD
     *
     * @mbggenerated
     */
    public String getTransCd() {
        return transCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.TRANS_CD
     *
     * @param transCd the value for tbl_manufacturer_para.TRANS_CD
     *
     * @mbggenerated
     */
    public void setTransCd(String transCd) {
        this.transCd = transCd == null ? null : transCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD1
     *
     * @return the value of tbl_manufacturer_para.EXTFLD1
     *
     * @mbggenerated
     */
    public String getExtfld1() {
        return extfld1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD1
     *
     * @param extfld1 the value for tbl_manufacturer_para.EXTFLD1
     *
     * @mbggenerated
     */
    public void setExtfld1(String extfld1) {
        this.extfld1 = extfld1 == null ? null : extfld1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD2
     *
     * @return the value of tbl_manufacturer_para.EXTFLD2
     *
     * @mbggenerated
     */
    public String getExtfld2() {
        return extfld2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD2
     *
     * @param extfld2 the value for tbl_manufacturer_para.EXTFLD2
     *
     * @mbggenerated
     */
    public void setExtfld2(String extfld2) {
        this.extfld2 = extfld2 == null ? null : extfld2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD3
     *
     * @return the value of tbl_manufacturer_para.EXTFLD3
     *
     * @mbggenerated
     */
    public String getExtfld3() {
        return extfld3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD3
     *
     * @param extfld3 the value for tbl_manufacturer_para.EXTFLD3
     *
     * @mbggenerated
     */
    public void setExtfld3(String extfld3) {
        this.extfld3 = extfld3 == null ? null : extfld3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD4
     *
     * @return the value of tbl_manufacturer_para.EXTFLD4
     *
     * @mbggenerated
     */
    public String getExtfld4() {
        return extfld4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD4
     *
     * @param extfld4 the value for tbl_manufacturer_para.EXTFLD4
     *
     * @mbggenerated
     */
    public void setExtfld4(String extfld4) {
        this.extfld4 = extfld4 == null ? null : extfld4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD5
     *
     * @return the value of tbl_manufacturer_para.EXTFLD5
     *
     * @mbggenerated
     */
    public String getExtfld5() {
        return extfld5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD5
     *
     * @param extfld5 the value for tbl_manufacturer_para.EXTFLD5
     *
     * @mbggenerated
     */
    public void setExtfld5(String extfld5) {
        this.extfld5 = extfld5 == null ? null : extfld5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD6
     *
     * @return the value of tbl_manufacturer_para.EXTFLD6
     *
     * @mbggenerated
     */
    public String getExtfld6() {
        return extfld6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD6
     *
     * @param extfld6 the value for tbl_manufacturer_para.EXTFLD6
     *
     * @mbggenerated
     */
    public void setExtfld6(String extfld6) {
        this.extfld6 = extfld6 == null ? null : extfld6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD7
     *
     * @return the value of tbl_manufacturer_para.EXTFLD7
     *
     * @mbggenerated
     */
    public String getExtfld7() {
        return extfld7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD7
     *
     * @param extfld7 the value for tbl_manufacturer_para.EXTFLD7
     *
     * @mbggenerated
     */
    public void setExtfld7(String extfld7) {
        this.extfld7 = extfld7 == null ? null : extfld7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD8
     *
     * @return the value of tbl_manufacturer_para.EXTFLD8
     *
     * @mbggenerated
     */
    public String getExtfld8() {
        return extfld8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD8
     *
     * @param extfld8 the value for tbl_manufacturer_para.EXTFLD8
     *
     * @mbggenerated
     */
    public void setExtfld8(String extfld8) {
        this.extfld8 = extfld8 == null ? null : extfld8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_manufacturer_para.EXTFLD9
     *
     * @return the value of tbl_manufacturer_para.EXTFLD9
     *
     * @mbggenerated
     */
    public String getExtfld9() {
        return extfld9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_manufacturer_para.EXTFLD9
     *
     * @param extfld9 the value for tbl_manufacturer_para.EXTFLD9
     *
     * @mbggenerated
     */
    public void setExtfld9(String extfld9) {
        this.extfld9 = extfld9 == null ? null : extfld9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_manufacturer_para
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", manufacturerCode=").append(manufacturerCode);
        sb.append(", manufacturerNm=").append(manufacturerNm);
        sb.append(", manufacturerTel=").append(manufacturerTel);
        sb.append(", transportationExpense=").append(transportationExpense);
        sb.append(", updateDt=").append(updateDt);
        sb.append(", transDt=").append(transDt);
        sb.append(", transTm=").append(transTm);
        sb.append(", version=").append(version);
        sb.append(", transCd=").append(transCd);
        sb.append(", extfld1=").append(extfld1);
        sb.append(", extfld2=").append(extfld2);
        sb.append(", extfld3=").append(extfld3);
        sb.append(", extfld4=").append(extfld4);
        sb.append(", extfld5=").append(extfld5);
        sb.append(", extfld6=").append(extfld6);
        sb.append(", extfld7=").append(extfld7);
        sb.append(", extfld8=").append(extfld8);
        sb.append(", extfld9=").append(extfld9);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}