package com.huayi.ljj.springcloud.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TblOrderRecordIn implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PRODUCT_NM
     *
     * @mbggenerated
     */
    private String productNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PRODUCT_KIND
     *
     * @mbggenerated
     */
    private String productKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    private String productThickness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    private String productLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PURCHASE_DT
     *
     * @mbggenerated
     */
    private String purchaseDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.TRANS_NO
     *
     * @mbggenerated
     */
    private String transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.SUPPLIER_NM
     *
     * @mbggenerated
     */
    private String supplierNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.SUPPLIER_CD
     *
     * @mbggenerated
     */
    private String supplierCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.TRANSPORTATION_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal transportationPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PRODUCT_OUT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal productOutPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PRODUCT_OUT_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal productOutAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.CARRY_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal carryPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.IN_STORAGE_WEIGHT
     *
     * @mbggenerated
     */
    private String inStorageWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.IN_STORAGE_NUM
     *
     * @mbggenerated
     */
    private String inStorageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.INVENTORY_NUM
     *
     * @mbggenerated
     */
    private String inventoryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.PIECE_COUNT
     *
     * @mbggenerated
     */
    private String pieceCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.COUNT
     *
     * @mbggenerated
     */
    private String count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.IN_STORAGE_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal inStoragePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.UPDATE_DT
     *
     * @mbggenerated
     */
    private String updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.CREAT_DT
     *
     * @mbggenerated
     */
    private String creatDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.TRANS_DT
     *
     * @mbggenerated
     */
    private String transDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.TRANS_TM
     *
     * @mbggenerated
     */
    private String transTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.TRANS_CD
     *
     * @mbggenerated
     */
    private String transCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.EXTFLD1
     *
     * @mbggenerated
     */
    private String extfld1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.EXTFLD2
     *
     * @mbggenerated
     */
    private String extfld2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_record_in.EXTFLD3
     *
     * @mbggenerated
     */
    private String extfld3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.ORDER_NO
     *
     * @return the value of tbl_order_record_in.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.ORDER_NO
     *
     * @param orderNo the value for tbl_order_record_in.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PRODUCT_NM
     *
     * @return the value of tbl_order_record_in.PRODUCT_NM
     *
     * @mbggenerated
     */
    public String getProductNm() {
        return productNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PRODUCT_NM
     *
     * @param productNm the value for tbl_order_record_in.PRODUCT_NM
     *
     * @mbggenerated
     */
    public void setProductNm(String productNm) {
        this.productNm = productNm == null ? null : productNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PRODUCT_KIND
     *
     * @return the value of tbl_order_record_in.PRODUCT_KIND
     *
     * @mbggenerated
     */
    public String getProductKind() {
        return productKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PRODUCT_KIND
     *
     * @param productKind the value for tbl_order_record_in.PRODUCT_KIND
     *
     * @mbggenerated
     */
    public void setProductKind(String productKind) {
        this.productKind = productKind == null ? null : productKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PRODUCT_THICKNESS
     *
     * @return the value of tbl_order_record_in.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    public String getProductThickness() {
        return productThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PRODUCT_THICKNESS
     *
     * @param productThickness the value for tbl_order_record_in.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    public void setProductThickness(String productThickness) {
        this.productThickness = productThickness == null ? null : productThickness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PRODUCT_LENGTH
     *
     * @return the value of tbl_order_record_in.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    public String getProductLength() {
        return productLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PRODUCT_LENGTH
     *
     * @param productLength the value for tbl_order_record_in.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    public void setProductLength(String productLength) {
        this.productLength = productLength == null ? null : productLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PURCHASE_DT
     *
     * @return the value of tbl_order_record_in.PURCHASE_DT
     *
     * @mbggenerated
     */
    public String getPurchaseDt() {
        return purchaseDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PURCHASE_DT
     *
     * @param purchaseDt the value for tbl_order_record_in.PURCHASE_DT
     *
     * @mbggenerated
     */
    public void setPurchaseDt(String purchaseDt) {
        this.purchaseDt = purchaseDt == null ? null : purchaseDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.TRANS_NO
     *
     * @return the value of tbl_order_record_in.TRANS_NO
     *
     * @mbggenerated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.TRANS_NO
     *
     * @param transNo the value for tbl_order_record_in.TRANS_NO
     *
     * @mbggenerated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.SUPPLIER_NM
     *
     * @return the value of tbl_order_record_in.SUPPLIER_NM
     *
     * @mbggenerated
     */
    public String getSupplierNm() {
        return supplierNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.SUPPLIER_NM
     *
     * @param supplierNm the value for tbl_order_record_in.SUPPLIER_NM
     *
     * @mbggenerated
     */
    public void setSupplierNm(String supplierNm) {
        this.supplierNm = supplierNm == null ? null : supplierNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.SUPPLIER_CD
     *
     * @return the value of tbl_order_record_in.SUPPLIER_CD
     *
     * @mbggenerated
     */
    public String getSupplierCd() {
        return supplierCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.SUPPLIER_CD
     *
     * @param supplierCd the value for tbl_order_record_in.SUPPLIER_CD
     *
     * @mbggenerated
     */
    public void setSupplierCd(String supplierCd) {
        this.supplierCd = supplierCd == null ? null : supplierCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.TRANSPORTATION_PRICE
     *
     * @return the value of tbl_order_record_in.TRANSPORTATION_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getTransportationPrice() {
        return transportationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.TRANSPORTATION_PRICE
     *
     * @param transportationPrice the value for tbl_order_record_in.TRANSPORTATION_PRICE
     *
     * @mbggenerated
     */
    public void setTransportationPrice(BigDecimal transportationPrice) {
        this.transportationPrice = transportationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PRODUCT_OUT_PRICE
     *
     * @return the value of tbl_order_record_in.PRODUCT_OUT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getProductOutPrice() {
        return productOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PRODUCT_OUT_PRICE
     *
     * @param productOutPrice the value for tbl_order_record_in.PRODUCT_OUT_PRICE
     *
     * @mbggenerated
     */
    public void setProductOutPrice(BigDecimal productOutPrice) {
        this.productOutPrice = productOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PRODUCT_OUT_AMOUNT
     *
     * @return the value of tbl_order_record_in.PRODUCT_OUT_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getProductOutAmount() {
        return productOutAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PRODUCT_OUT_AMOUNT
     *
     * @param productOutAmount the value for tbl_order_record_in.PRODUCT_OUT_AMOUNT
     *
     * @mbggenerated
     */
    public void setProductOutAmount(BigDecimal productOutAmount) {
        this.productOutAmount = productOutAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.CARRY_PRICE
     *
     * @return the value of tbl_order_record_in.CARRY_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getCarryPrice() {
        return carryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.CARRY_PRICE
     *
     * @param carryPrice the value for tbl_order_record_in.CARRY_PRICE
     *
     * @mbggenerated
     */
    public void setCarryPrice(BigDecimal carryPrice) {
        this.carryPrice = carryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.IN_STORAGE_WEIGHT
     *
     * @return the value of tbl_order_record_in.IN_STORAGE_WEIGHT
     *
     * @mbggenerated
     */
    public String getInStorageWeight() {
        return inStorageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.IN_STORAGE_WEIGHT
     *
     * @param inStorageWeight the value for tbl_order_record_in.IN_STORAGE_WEIGHT
     *
     * @mbggenerated
     */
    public void setInStorageWeight(String inStorageWeight) {
        this.inStorageWeight = inStorageWeight == null ? null : inStorageWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.IN_STORAGE_NUM
     *
     * @return the value of tbl_order_record_in.IN_STORAGE_NUM
     *
     * @mbggenerated
     */
    public String getInStorageNum() {
        return inStorageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.IN_STORAGE_NUM
     *
     * @param inStorageNum the value for tbl_order_record_in.IN_STORAGE_NUM
     *
     * @mbggenerated
     */
    public void setInStorageNum(String inStorageNum) {
        this.inStorageNum = inStorageNum == null ? null : inStorageNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.INVENTORY_NUM
     *
     * @return the value of tbl_order_record_in.INVENTORY_NUM
     *
     * @mbggenerated
     */
    public String getInventoryNum() {
        return inventoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.INVENTORY_NUM
     *
     * @param inventoryNum the value for tbl_order_record_in.INVENTORY_NUM
     *
     * @mbggenerated
     */
    public void setInventoryNum(String inventoryNum) {
        this.inventoryNum = inventoryNum == null ? null : inventoryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.PIECE_COUNT
     *
     * @return the value of tbl_order_record_in.PIECE_COUNT
     *
     * @mbggenerated
     */
    public String getPieceCount() {
        return pieceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.PIECE_COUNT
     *
     * @param pieceCount the value for tbl_order_record_in.PIECE_COUNT
     *
     * @mbggenerated
     */
    public void setPieceCount(String pieceCount) {
        this.pieceCount = pieceCount == null ? null : pieceCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.COUNT
     *
     * @return the value of tbl_order_record_in.COUNT
     *
     * @mbggenerated
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.COUNT
     *
     * @param count the value for tbl_order_record_in.COUNT
     *
     * @mbggenerated
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.IN_STORAGE_PRICE
     *
     * @return the value of tbl_order_record_in.IN_STORAGE_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getInStoragePrice() {
        return inStoragePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.IN_STORAGE_PRICE
     *
     * @param inStoragePrice the value for tbl_order_record_in.IN_STORAGE_PRICE
     *
     * @mbggenerated
     */
    public void setInStoragePrice(BigDecimal inStoragePrice) {
        this.inStoragePrice = inStoragePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.UPDATE_DT
     *
     * @return the value of tbl_order_record_in.UPDATE_DT
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.UPDATE_DT
     *
     * @param updateDt the value for tbl_order_record_in.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.CREAT_DT
     *
     * @return the value of tbl_order_record_in.CREAT_DT
     *
     * @mbggenerated
     */
    public String getCreatDt() {
        return creatDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.CREAT_DT
     *
     * @param creatDt the value for tbl_order_record_in.CREAT_DT
     *
     * @mbggenerated
     */
    public void setCreatDt(String creatDt) {
        this.creatDt = creatDt == null ? null : creatDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.TRANS_DT
     *
     * @return the value of tbl_order_record_in.TRANS_DT
     *
     * @mbggenerated
     */
    public String getTransDt() {
        return transDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.TRANS_DT
     *
     * @param transDt the value for tbl_order_record_in.TRANS_DT
     *
     * @mbggenerated
     */
    public void setTransDt(String transDt) {
        this.transDt = transDt == null ? null : transDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.TRANS_TM
     *
     * @return the value of tbl_order_record_in.TRANS_TM
     *
     * @mbggenerated
     */
    public String getTransTm() {
        return transTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.TRANS_TM
     *
     * @param transTm the value for tbl_order_record_in.TRANS_TM
     *
     * @mbggenerated
     */
    public void setTransTm(String transTm) {
        this.transTm = transTm == null ? null : transTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.VERSION
     *
     * @return the value of tbl_order_record_in.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.VERSION
     *
     * @param version the value for tbl_order_record_in.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.TRANS_CD
     *
     * @return the value of tbl_order_record_in.TRANS_CD
     *
     * @mbggenerated
     */
    public String getTransCd() {
        return transCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.TRANS_CD
     *
     * @param transCd the value for tbl_order_record_in.TRANS_CD
     *
     * @mbggenerated
     */
    public void setTransCd(String transCd) {
        this.transCd = transCd == null ? null : transCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.EXTFLD1
     *
     * @return the value of tbl_order_record_in.EXTFLD1
     *
     * @mbggenerated
     */
    public String getExtfld1() {
        return extfld1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.EXTFLD1
     *
     * @param extfld1 the value for tbl_order_record_in.EXTFLD1
     *
     * @mbggenerated
     */
    public void setExtfld1(String extfld1) {
        this.extfld1 = extfld1 == null ? null : extfld1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.EXTFLD2
     *
     * @return the value of tbl_order_record_in.EXTFLD2
     *
     * @mbggenerated
     */
    public String getExtfld2() {
        return extfld2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.EXTFLD2
     *
     * @param extfld2 the value for tbl_order_record_in.EXTFLD2
     *
     * @mbggenerated
     */
    public void setExtfld2(String extfld2) {
        this.extfld2 = extfld2 == null ? null : extfld2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order_record_in.EXTFLD3
     *
     * @return the value of tbl_order_record_in.EXTFLD3
     *
     * @mbggenerated
     */
    public String getExtfld3() {
        return extfld3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order_record_in.EXTFLD3
     *
     * @param extfld3 the value for tbl_order_record_in.EXTFLD3
     *
     * @mbggenerated
     */
    public void setExtfld3(String extfld3) {
        this.extfld3 = extfld3 == null ? null : extfld3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_record_in
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderNo=").append(orderNo);
        sb.append(", productNm=").append(productNm);
        sb.append(", productKind=").append(productKind);
        sb.append(", productThickness=").append(productThickness);
        sb.append(", productLength=").append(productLength);
        sb.append(", purchaseDt=").append(purchaseDt);
        sb.append(", transNo=").append(transNo);
        sb.append(", supplierNm=").append(supplierNm);
        sb.append(", supplierCd=").append(supplierCd);
        sb.append(", transportationPrice=").append(transportationPrice);
        sb.append(", productOutPrice=").append(productOutPrice);
        sb.append(", productOutAmount=").append(productOutAmount);
        sb.append(", carryPrice=").append(carryPrice);
        sb.append(", inStorageWeight=").append(inStorageWeight);
        sb.append(", inStorageNum=").append(inStorageNum);
        sb.append(", inventoryNum=").append(inventoryNum);
        sb.append(", pieceCount=").append(pieceCount);
        sb.append(", count=").append(count);
        sb.append(", inStoragePrice=").append(inStoragePrice);
        sb.append(", updateDt=").append(updateDt);
        sb.append(", creatDt=").append(creatDt);
        sb.append(", transDt=").append(transDt);
        sb.append(", transTm=").append(transTm);
        sb.append(", version=").append(version);
        sb.append(", transCd=").append(transCd);
        sb.append(", extfld1=").append(extfld1);
        sb.append(", extfld2=").append(extfld2);
        sb.append(", extfld3=").append(extfld3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}