package com.huayi.ljj.springcloud.model;

import java.util.ArrayList;
import java.util.List;

public class TblProdNameParaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public TblProdNameParaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductNoIsNull() {
            addCriterion("PRODUCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("PRODUCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("PRODUCT_NO =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("PRODUCT_NO <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("PRODUCT_NO >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NO >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("PRODUCT_NO <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NO <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("PRODUCT_NO like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("PRODUCT_NO not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("PRODUCT_NO in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("PRODUCT_NO not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("PRODUCT_NO between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NO not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNmIsNull() {
            addCriterion("PRODUCT_NM is null");
            return (Criteria) this;
        }

        public Criteria andProductNmIsNotNull() {
            addCriterion("PRODUCT_NM is not null");
            return (Criteria) this;
        }

        public Criteria andProductNmEqualTo(String value) {
            addCriterion("PRODUCT_NM =", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmNotEqualTo(String value) {
            addCriterion("PRODUCT_NM <>", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmGreaterThan(String value) {
            addCriterion("PRODUCT_NM >", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NM >=", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmLessThan(String value) {
            addCriterion("PRODUCT_NM <", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NM <=", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmLike(String value) {
            addCriterion("PRODUCT_NM like", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmNotLike(String value) {
            addCriterion("PRODUCT_NM not like", value, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmIn(List<String> values) {
            addCriterion("PRODUCT_NM in", values, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmNotIn(List<String> values) {
            addCriterion("PRODUCT_NM not in", values, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmBetween(String value1, String value2) {
            addCriterion("PRODUCT_NM between", value1, value2, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductNmNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NM not between", value1, value2, "productNm");
            return (Criteria) this;
        }

        public Criteria andProductKindIsNull() {
            addCriterion("PRODUCT_KIND is null");
            return (Criteria) this;
        }

        public Criteria andProductKindIsNotNull() {
            addCriterion("PRODUCT_KIND is not null");
            return (Criteria) this;
        }

        public Criteria andProductKindEqualTo(String value) {
            addCriterion("PRODUCT_KIND =", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindNotEqualTo(String value) {
            addCriterion("PRODUCT_KIND <>", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindGreaterThan(String value) {
            addCriterion("PRODUCT_KIND >", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_KIND >=", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindLessThan(String value) {
            addCriterion("PRODUCT_KIND <", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_KIND <=", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindLike(String value) {
            addCriterion("PRODUCT_KIND like", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindNotLike(String value) {
            addCriterion("PRODUCT_KIND not like", value, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindIn(List<String> values) {
            addCriterion("PRODUCT_KIND in", values, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindNotIn(List<String> values) {
            addCriterion("PRODUCT_KIND not in", values, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindBetween(String value1, String value2) {
            addCriterion("PRODUCT_KIND between", value1, value2, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductKindNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_KIND not between", value1, value2, "productKind");
            return (Criteria) this;
        }

        public Criteria andProductThicknessIsNull() {
            addCriterion("PRODUCT_THICKNESS is null");
            return (Criteria) this;
        }

        public Criteria andProductThicknessIsNotNull() {
            addCriterion("PRODUCT_THICKNESS is not null");
            return (Criteria) this;
        }

        public Criteria andProductThicknessEqualTo(String value) {
            addCriterion("PRODUCT_THICKNESS =", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessNotEqualTo(String value) {
            addCriterion("PRODUCT_THICKNESS <>", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessGreaterThan(String value) {
            addCriterion("PRODUCT_THICKNESS >", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_THICKNESS >=", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessLessThan(String value) {
            addCriterion("PRODUCT_THICKNESS <", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_THICKNESS <=", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessLike(String value) {
            addCriterion("PRODUCT_THICKNESS like", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessNotLike(String value) {
            addCriterion("PRODUCT_THICKNESS not like", value, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessIn(List<String> values) {
            addCriterion("PRODUCT_THICKNESS in", values, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessNotIn(List<String> values) {
            addCriterion("PRODUCT_THICKNESS not in", values, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessBetween(String value1, String value2) {
            addCriterion("PRODUCT_THICKNESS between", value1, value2, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductThicknessNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_THICKNESS not between", value1, value2, "productThickness");
            return (Criteria) this;
        }

        public Criteria andProductLengthIsNull() {
            addCriterion("PRODUCT_LENGTH is null");
            return (Criteria) this;
        }

        public Criteria andProductLengthIsNotNull() {
            addCriterion("PRODUCT_LENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andProductLengthEqualTo(String value) {
            addCriterion("PRODUCT_LENGTH =", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotEqualTo(String value) {
            addCriterion("PRODUCT_LENGTH <>", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthGreaterThan(String value) {
            addCriterion("PRODUCT_LENGTH >", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_LENGTH >=", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthLessThan(String value) {
            addCriterion("PRODUCT_LENGTH <", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_LENGTH <=", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthLike(String value) {
            addCriterion("PRODUCT_LENGTH like", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotLike(String value) {
            addCriterion("PRODUCT_LENGTH not like", value, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthIn(List<String> values) {
            addCriterion("PRODUCT_LENGTH in", values, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotIn(List<String> values) {
            addCriterion("PRODUCT_LENGTH not in", values, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthBetween(String value1, String value2) {
            addCriterion("PRODUCT_LENGTH between", value1, value2, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductLengthNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_LENGTH not between", value1, value2, "productLength");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightIsNull() {
            addCriterion("PRODUCT_THEORY_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightIsNotNull() {
            addCriterion("PRODUCT_THEORY_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightEqualTo(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT =", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightNotEqualTo(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT <>", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightGreaterThan(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT >", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT >=", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightLessThan(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT <", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT <=", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightLike(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT like", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightNotLike(String value) {
            addCriterion("PRODUCT_THEORY_WEIGHT not like", value, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightIn(List<String> values) {
            addCriterion("PRODUCT_THEORY_WEIGHT in", values, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightNotIn(List<String> values) {
            addCriterion("PRODUCT_THEORY_WEIGHT not in", values, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightBetween(String value1, String value2) {
            addCriterion("PRODUCT_THEORY_WEIGHT between", value1, value2, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductTheoryWeightNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_THEORY_WEIGHT not between", value1, value2, "productTheoryWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightIsNull() {
            addCriterion("PRODUCT_ACTUL_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightIsNotNull() {
            addCriterion("PRODUCT_ACTUL_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightEqualTo(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT =", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightNotEqualTo(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT <>", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightGreaterThan(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT >", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT >=", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightLessThan(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT <", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT <=", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightLike(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT like", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightNotLike(String value) {
            addCriterion("PRODUCT_ACTUL_WEIGHT not like", value, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightIn(List<String> values) {
            addCriterion("PRODUCT_ACTUL_WEIGHT in", values, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightNotIn(List<String> values) {
            addCriterion("PRODUCT_ACTUL_WEIGHT not in", values, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightBetween(String value1, String value2) {
            addCriterion("PRODUCT_ACTUL_WEIGHT between", value1, value2, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andProductActulWeightNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_ACTUL_WEIGHT not between", value1, value2, "productActulWeight");
            return (Criteria) this;
        }

        public Criteria andCreatDtIsNull() {
            addCriterion("CREAT_DT is null");
            return (Criteria) this;
        }

        public Criteria andCreatDtIsNotNull() {
            addCriterion("CREAT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatDtEqualTo(String value) {
            addCriterion("CREAT_DT =", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtNotEqualTo(String value) {
            addCriterion("CREAT_DT <>", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtGreaterThan(String value) {
            addCriterion("CREAT_DT >", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtGreaterThanOrEqualTo(String value) {
            addCriterion("CREAT_DT >=", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtLessThan(String value) {
            addCriterion("CREAT_DT <", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtLessThanOrEqualTo(String value) {
            addCriterion("CREAT_DT <=", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtLike(String value) {
            addCriterion("CREAT_DT like", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtNotLike(String value) {
            addCriterion("CREAT_DT not like", value, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtIn(List<String> values) {
            addCriterion("CREAT_DT in", values, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtNotIn(List<String> values) {
            addCriterion("CREAT_DT not in", values, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtBetween(String value1, String value2) {
            addCriterion("CREAT_DT between", value1, value2, "creatDt");
            return (Criteria) this;
        }

        public Criteria andCreatDtNotBetween(String value1, String value2) {
            addCriterion("CREAT_DT not between", value1, value2, "creatDt");
            return (Criteria) this;
        }

        public Criteria andTransDtIsNull() {
            addCriterion("TRANS_DT is null");
            return (Criteria) this;
        }

        public Criteria andTransDtIsNotNull() {
            addCriterion("TRANS_DT is not null");
            return (Criteria) this;
        }

        public Criteria andTransDtEqualTo(String value) {
            addCriterion("TRANS_DT =", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotEqualTo(String value) {
            addCriterion("TRANS_DT <>", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtGreaterThan(String value) {
            addCriterion("TRANS_DT >", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_DT >=", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLessThan(String value) {
            addCriterion("TRANS_DT <", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLessThanOrEqualTo(String value) {
            addCriterion("TRANS_DT <=", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLike(String value) {
            addCriterion("TRANS_DT like", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotLike(String value) {
            addCriterion("TRANS_DT not like", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtIn(List<String> values) {
            addCriterion("TRANS_DT in", values, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotIn(List<String> values) {
            addCriterion("TRANS_DT not in", values, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtBetween(String value1, String value2) {
            addCriterion("TRANS_DT between", value1, value2, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotBetween(String value1, String value2) {
            addCriterion("TRANS_DT not between", value1, value2, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransTmIsNull() {
            addCriterion("TRANS_TM is null");
            return (Criteria) this;
        }

        public Criteria andTransTmIsNotNull() {
            addCriterion("TRANS_TM is not null");
            return (Criteria) this;
        }

        public Criteria andTransTmEqualTo(String value) {
            addCriterion("TRANS_TM =", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotEqualTo(String value) {
            addCriterion("TRANS_TM <>", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmGreaterThan(String value) {
            addCriterion("TRANS_TM >", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmGreaterThanOrEqualTo(String value) {
            addCriterion("TRANS_TM >=", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmLessThan(String value) {
            addCriterion("TRANS_TM <", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmLessThanOrEqualTo(String value) {
            addCriterion("TRANS_TM <=", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmLike(String value) {
            addCriterion("TRANS_TM like", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotLike(String value) {
            addCriterion("TRANS_TM not like", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmIn(List<String> values) {
            addCriterion("TRANS_TM in", values, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotIn(List<String> values) {
            addCriterion("TRANS_TM not in", values, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmBetween(String value1, String value2) {
            addCriterion("TRANS_TM between", value1, value2, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotBetween(String value1, String value2) {
            addCriterion("TRANS_TM not between", value1, value2, "transTm");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andExtfld1IsNull() {
            addCriterion("EXTFLD1 is null");
            return (Criteria) this;
        }

        public Criteria andExtfld1IsNotNull() {
            addCriterion("EXTFLD1 is not null");
            return (Criteria) this;
        }

        public Criteria andExtfld1EqualTo(String value) {
            addCriterion("EXTFLD1 =", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1NotEqualTo(String value) {
            addCriterion("EXTFLD1 <>", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1GreaterThan(String value) {
            addCriterion("EXTFLD1 >", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1GreaterThanOrEqualTo(String value) {
            addCriterion("EXTFLD1 >=", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1LessThan(String value) {
            addCriterion("EXTFLD1 <", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1LessThanOrEqualTo(String value) {
            addCriterion("EXTFLD1 <=", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1Like(String value) {
            addCriterion("EXTFLD1 like", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1NotLike(String value) {
            addCriterion("EXTFLD1 not like", value, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1In(List<String> values) {
            addCriterion("EXTFLD1 in", values, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1NotIn(List<String> values) {
            addCriterion("EXTFLD1 not in", values, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1Between(String value1, String value2) {
            addCriterion("EXTFLD1 between", value1, value2, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld1NotBetween(String value1, String value2) {
            addCriterion("EXTFLD1 not between", value1, value2, "extfld1");
            return (Criteria) this;
        }

        public Criteria andExtfld2IsNull() {
            addCriterion("EXTFLD2 is null");
            return (Criteria) this;
        }

        public Criteria andExtfld2IsNotNull() {
            addCriterion("EXTFLD2 is not null");
            return (Criteria) this;
        }

        public Criteria andExtfld2EqualTo(String value) {
            addCriterion("EXTFLD2 =", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2NotEqualTo(String value) {
            addCriterion("EXTFLD2 <>", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2GreaterThan(String value) {
            addCriterion("EXTFLD2 >", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2GreaterThanOrEqualTo(String value) {
            addCriterion("EXTFLD2 >=", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2LessThan(String value) {
            addCriterion("EXTFLD2 <", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2LessThanOrEqualTo(String value) {
            addCriterion("EXTFLD2 <=", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2Like(String value) {
            addCriterion("EXTFLD2 like", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2NotLike(String value) {
            addCriterion("EXTFLD2 not like", value, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2In(List<String> values) {
            addCriterion("EXTFLD2 in", values, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2NotIn(List<String> values) {
            addCriterion("EXTFLD2 not in", values, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2Between(String value1, String value2) {
            addCriterion("EXTFLD2 between", value1, value2, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld2NotBetween(String value1, String value2) {
            addCriterion("EXTFLD2 not between", value1, value2, "extfld2");
            return (Criteria) this;
        }

        public Criteria andExtfld3IsNull() {
            addCriterion("EXTFLD3 is null");
            return (Criteria) this;
        }

        public Criteria andExtfld3IsNotNull() {
            addCriterion("EXTFLD3 is not null");
            return (Criteria) this;
        }

        public Criteria andExtfld3EqualTo(String value) {
            addCriterion("EXTFLD3 =", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3NotEqualTo(String value) {
            addCriterion("EXTFLD3 <>", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3GreaterThan(String value) {
            addCriterion("EXTFLD3 >", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3GreaterThanOrEqualTo(String value) {
            addCriterion("EXTFLD3 >=", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3LessThan(String value) {
            addCriterion("EXTFLD3 <", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3LessThanOrEqualTo(String value) {
            addCriterion("EXTFLD3 <=", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3Like(String value) {
            addCriterion("EXTFLD3 like", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3NotLike(String value) {
            addCriterion("EXTFLD3 not like", value, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3In(List<String> values) {
            addCriterion("EXTFLD3 in", values, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3NotIn(List<String> values) {
            addCriterion("EXTFLD3 not in", values, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3Between(String value1, String value2) {
            addCriterion("EXTFLD3 between", value1, value2, "extfld3");
            return (Criteria) this;
        }

        public Criteria andExtfld3NotBetween(String value1, String value2) {
            addCriterion("EXTFLD3 not between", value1, value2, "extfld3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}