package com.huayi.ljj.springcloud.model;

import java.io.Serializable;

public class TblProdNamePara implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_NO
     *
     * @mbggenerated
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_NM
     *
     * @mbggenerated
     */
    private String productNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_KIND
     *
     * @mbggenerated
     */
    private String productKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    private String productThickness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    private String productLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_THEORY_WEIGHT
     *
     * @mbggenerated
     */
    private String productTheoryWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.PRODUCT_ACTUL_WEIGHT
     *
     * @mbggenerated
     */
    private String productActulWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.CREAT_DT
     *
     * @mbggenerated
     */
    private String creatDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.TRANS_DT
     *
     * @mbggenerated
     */
    private String transDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.TRANS_TM
     *
     * @mbggenerated
     */
    private String transTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.EXTFLD1
     *
     * @mbggenerated
     */
    private String extfld1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.EXTFLD2
     *
     * @mbggenerated
     */
    private String extfld2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_name_para.EXTFLD3
     *
     * @mbggenerated
     */
    private String extfld3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_NO
     *
     * @return the value of tbl_prod_name_para.PRODUCT_NO
     *
     * @mbggenerated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_NO
     *
     * @param productNo the value for tbl_prod_name_para.PRODUCT_NO
     *
     * @mbggenerated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_NM
     *
     * @return the value of tbl_prod_name_para.PRODUCT_NM
     *
     * @mbggenerated
     */
    public String getProductNm() {
        return productNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_NM
     *
     * @param productNm the value for tbl_prod_name_para.PRODUCT_NM
     *
     * @mbggenerated
     */
    public void setProductNm(String productNm) {
        this.productNm = productNm == null ? null : productNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_KIND
     *
     * @return the value of tbl_prod_name_para.PRODUCT_KIND
     *
     * @mbggenerated
     */
    public String getProductKind() {
        return productKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_KIND
     *
     * @param productKind the value for tbl_prod_name_para.PRODUCT_KIND
     *
     * @mbggenerated
     */
    public void setProductKind(String productKind) {
        this.productKind = productKind == null ? null : productKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_THICKNESS
     *
     * @return the value of tbl_prod_name_para.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    public String getProductThickness() {
        return productThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_THICKNESS
     *
     * @param productThickness the value for tbl_prod_name_para.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    public void setProductThickness(String productThickness) {
        this.productThickness = productThickness == null ? null : productThickness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_LENGTH
     *
     * @return the value of tbl_prod_name_para.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    public String getProductLength() {
        return productLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_LENGTH
     *
     * @param productLength the value for tbl_prod_name_para.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    public void setProductLength(String productLength) {
        this.productLength = productLength == null ? null : productLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_THEORY_WEIGHT
     *
     * @return the value of tbl_prod_name_para.PRODUCT_THEORY_WEIGHT
     *
     * @mbggenerated
     */
    public String getProductTheoryWeight() {
        return productTheoryWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_THEORY_WEIGHT
     *
     * @param productTheoryWeight the value for tbl_prod_name_para.PRODUCT_THEORY_WEIGHT
     *
     * @mbggenerated
     */
    public void setProductTheoryWeight(String productTheoryWeight) {
        this.productTheoryWeight = productTheoryWeight == null ? null : productTheoryWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.PRODUCT_ACTUL_WEIGHT
     *
     * @return the value of tbl_prod_name_para.PRODUCT_ACTUL_WEIGHT
     *
     * @mbggenerated
     */
    public String getProductActulWeight() {
        return productActulWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.PRODUCT_ACTUL_WEIGHT
     *
     * @param productActulWeight the value for tbl_prod_name_para.PRODUCT_ACTUL_WEIGHT
     *
     * @mbggenerated
     */
    public void setProductActulWeight(String productActulWeight) {
        this.productActulWeight = productActulWeight == null ? null : productActulWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.CREAT_DT
     *
     * @return the value of tbl_prod_name_para.CREAT_DT
     *
     * @mbggenerated
     */
    public String getCreatDt() {
        return creatDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.CREAT_DT
     *
     * @param creatDt the value for tbl_prod_name_para.CREAT_DT
     *
     * @mbggenerated
     */
    public void setCreatDt(String creatDt) {
        this.creatDt = creatDt == null ? null : creatDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.TRANS_DT
     *
     * @return the value of tbl_prod_name_para.TRANS_DT
     *
     * @mbggenerated
     */
    public String getTransDt() {
        return transDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.TRANS_DT
     *
     * @param transDt the value for tbl_prod_name_para.TRANS_DT
     *
     * @mbggenerated
     */
    public void setTransDt(String transDt) {
        this.transDt = transDt == null ? null : transDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.TRANS_TM
     *
     * @return the value of tbl_prod_name_para.TRANS_TM
     *
     * @mbggenerated
     */
    public String getTransTm() {
        return transTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.TRANS_TM
     *
     * @param transTm the value for tbl_prod_name_para.TRANS_TM
     *
     * @mbggenerated
     */
    public void setTransTm(String transTm) {
        this.transTm = transTm == null ? null : transTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.VERSION
     *
     * @return the value of tbl_prod_name_para.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.VERSION
     *
     * @param version the value for tbl_prod_name_para.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.EXTFLD1
     *
     * @return the value of tbl_prod_name_para.EXTFLD1
     *
     * @mbggenerated
     */
    public String getExtfld1() {
        return extfld1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.EXTFLD1
     *
     * @param extfld1 the value for tbl_prod_name_para.EXTFLD1
     *
     * @mbggenerated
     */
    public void setExtfld1(String extfld1) {
        this.extfld1 = extfld1 == null ? null : extfld1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.EXTFLD2
     *
     * @return the value of tbl_prod_name_para.EXTFLD2
     *
     * @mbggenerated
     */
    public String getExtfld2() {
        return extfld2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.EXTFLD2
     *
     * @param extfld2 the value for tbl_prod_name_para.EXTFLD2
     *
     * @mbggenerated
     */
    public void setExtfld2(String extfld2) {
        this.extfld2 = extfld2 == null ? null : extfld2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_name_para.EXTFLD3
     *
     * @return the value of tbl_prod_name_para.EXTFLD3
     *
     * @mbggenerated
     */
    public String getExtfld3() {
        return extfld3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_name_para.EXTFLD3
     *
     * @param extfld3 the value for tbl_prod_name_para.EXTFLD3
     *
     * @mbggenerated
     */
    public void setExtfld3(String extfld3) {
        this.extfld3 = extfld3 == null ? null : extfld3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_name_para
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productNo=").append(productNo);
        sb.append(", productNm=").append(productNm);
        sb.append(", productKind=").append(productKind);
        sb.append(", productThickness=").append(productThickness);
        sb.append(", productLength=").append(productLength);
        sb.append(", productTheoryWeight=").append(productTheoryWeight);
        sb.append(", productActulWeight=").append(productActulWeight);
        sb.append(", creatDt=").append(creatDt);
        sb.append(", transDt=").append(transDt);
        sb.append(", transTm=").append(transTm);
        sb.append(", version=").append(version);
        sb.append(", extfld1=").append(extfld1);
        sb.append(", extfld2=").append(extfld2);
        sb.append(", extfld3=").append(extfld3);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}