package com.huayi.ljj.springcloud.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TblProdInventory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.PRODUCT_NM
     *
     * @mbggenerated
     */
    private String productNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.PRODUCT_KIND
     *
     * @mbggenerated
     */
    private String productKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    private String productThickness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    private String productLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.CARR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal carrPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.IN_STORAGE_WEIGHT
     *
     * @mbggenerated
     */
    private String inStorageWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.IN_STORAGE_NUM
     *
     * @mbggenerated
     */
    private String inStorageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.INVENTORY_NUM
     *
     * @mbggenerated
     */
    private String inventoryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.IN_STORAGE_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal inStoragePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.UPDATE_DT
     *
     * @mbggenerated
     */
    private String updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.CREATE_DT
     *
     * @mbggenerated
     */
    private String createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.TRANS_TM
     *
     * @mbggenerated
     */
    private String transTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.TRANS_DT
     *
     * @mbggenerated
     */
    private String transDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_prod_inventory.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.PRODUCT_NM
     *
     * @return the value of tbl_prod_inventory.PRODUCT_NM
     *
     * @mbggenerated
     */
    public String getProductNm() {
        return productNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.PRODUCT_NM
     *
     * @param productNm the value for tbl_prod_inventory.PRODUCT_NM
     *
     * @mbggenerated
     */
    public void setProductNm(String productNm) {
        this.productNm = productNm == null ? null : productNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.PRODUCT_KIND
     *
     * @return the value of tbl_prod_inventory.PRODUCT_KIND
     *
     * @mbggenerated
     */
    public String getProductKind() {
        return productKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.PRODUCT_KIND
     *
     * @param productKind the value for tbl_prod_inventory.PRODUCT_KIND
     *
     * @mbggenerated
     */
    public void setProductKind(String productKind) {
        this.productKind = productKind == null ? null : productKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.PRODUCT_THICKNESS
     *
     * @return the value of tbl_prod_inventory.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    public String getProductThickness() {
        return productThickness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.PRODUCT_THICKNESS
     *
     * @param productThickness the value for tbl_prod_inventory.PRODUCT_THICKNESS
     *
     * @mbggenerated
     */
    public void setProductThickness(String productThickness) {
        this.productThickness = productThickness == null ? null : productThickness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.PRODUCT_LENGTH
     *
     * @return the value of tbl_prod_inventory.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    public String getProductLength() {
        return productLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.PRODUCT_LENGTH
     *
     * @param productLength the value for tbl_prod_inventory.PRODUCT_LENGTH
     *
     * @mbggenerated
     */
    public void setProductLength(String productLength) {
        this.productLength = productLength == null ? null : productLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.CARR_PRICE
     *
     * @return the value of tbl_prod_inventory.CARR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getCarrPrice() {
        return carrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.CARR_PRICE
     *
     * @param carrPrice the value for tbl_prod_inventory.CARR_PRICE
     *
     * @mbggenerated
     */
    public void setCarrPrice(BigDecimal carrPrice) {
        this.carrPrice = carrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.IN_STORAGE_WEIGHT
     *
     * @return the value of tbl_prod_inventory.IN_STORAGE_WEIGHT
     *
     * @mbggenerated
     */
    public String getInStorageWeight() {
        return inStorageWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.IN_STORAGE_WEIGHT
     *
     * @param inStorageWeight the value for tbl_prod_inventory.IN_STORAGE_WEIGHT
     *
     * @mbggenerated
     */
    public void setInStorageWeight(String inStorageWeight) {
        this.inStorageWeight = inStorageWeight == null ? null : inStorageWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.IN_STORAGE_NUM
     *
     * @return the value of tbl_prod_inventory.IN_STORAGE_NUM
     *
     * @mbggenerated
     */
    public String getInStorageNum() {
        return inStorageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.IN_STORAGE_NUM
     *
     * @param inStorageNum the value for tbl_prod_inventory.IN_STORAGE_NUM
     *
     * @mbggenerated
     */
    public void setInStorageNum(String inStorageNum) {
        this.inStorageNum = inStorageNum == null ? null : inStorageNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.INVENTORY_NUM
     *
     * @return the value of tbl_prod_inventory.INVENTORY_NUM
     *
     * @mbggenerated
     */
    public String getInventoryNum() {
        return inventoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.INVENTORY_NUM
     *
     * @param inventoryNum the value for tbl_prod_inventory.INVENTORY_NUM
     *
     * @mbggenerated
     */
    public void setInventoryNum(String inventoryNum) {
        this.inventoryNum = inventoryNum == null ? null : inventoryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.IN_STORAGE_PRICE
     *
     * @return the value of tbl_prod_inventory.IN_STORAGE_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getInStoragePrice() {
        return inStoragePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.IN_STORAGE_PRICE
     *
     * @param inStoragePrice the value for tbl_prod_inventory.IN_STORAGE_PRICE
     *
     * @mbggenerated
     */
    public void setInStoragePrice(BigDecimal inStoragePrice) {
        this.inStoragePrice = inStoragePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.UPDATE_DT
     *
     * @return the value of tbl_prod_inventory.UPDATE_DT
     *
     * @mbggenerated
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.UPDATE_DT
     *
     * @param updateDt the value for tbl_prod_inventory.UPDATE_DT
     *
     * @mbggenerated
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.CREATE_DT
     *
     * @return the value of tbl_prod_inventory.CREATE_DT
     *
     * @mbggenerated
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.CREATE_DT
     *
     * @param createDt the value for tbl_prod_inventory.CREATE_DT
     *
     * @mbggenerated
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.TRANS_TM
     *
     * @return the value of tbl_prod_inventory.TRANS_TM
     *
     * @mbggenerated
     */
    public String getTransTm() {
        return transTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.TRANS_TM
     *
     * @param transTm the value for tbl_prod_inventory.TRANS_TM
     *
     * @mbggenerated
     */
    public void setTransTm(String transTm) {
        this.transTm = transTm == null ? null : transTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.TRANS_DT
     *
     * @return the value of tbl_prod_inventory.TRANS_DT
     *
     * @mbggenerated
     */
    public String getTransDt() {
        return transDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.TRANS_DT
     *
     * @param transDt the value for tbl_prod_inventory.TRANS_DT
     *
     * @mbggenerated
     */
    public void setTransDt(String transDt) {
        this.transDt = transDt == null ? null : transDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_prod_inventory.VERSION
     *
     * @return the value of tbl_prod_inventory.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_prod_inventory.VERSION
     *
     * @param version the value for tbl_prod_inventory.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_prod_inventory
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productNm=").append(productNm);
        sb.append(", productKind=").append(productKind);
        sb.append(", productThickness=").append(productThickness);
        sb.append(", productLength=").append(productLength);
        sb.append(", carrPrice=").append(carrPrice);
        sb.append(", inStorageWeight=").append(inStorageWeight);
        sb.append(", inStorageNum=").append(inStorageNum);
        sb.append(", inventoryNum=").append(inventoryNum);
        sb.append(", inStoragePrice=").append(inStoragePrice);
        sb.append(", updateDt=").append(updateDt);
        sb.append(", createDt=").append(createDt);
        sb.append(", transTm=").append(transTm);
        sb.append(", transDt=").append(transDt);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}