package com.huayi.ljj.springcloud.model;

import java.io.Serializable;

public class TblTransLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.TRANS_NO
     *
     * @mbggenerated
     */
    private String transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.TRANS_DT
     *
     * @mbggenerated
     */
    private String transDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.TRANS_TM
     *
     * @mbggenerated
     */
    private String transTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.EVENT
     *
     * @mbggenerated
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.PROD_CD
     *
     * @mbggenerated
     */
    private String prodCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.OPERATOR_NM
     *
     * @mbggenerated
     */
    private String operatorNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_trans_log.OPERATOR_ID
     *
     * @mbggenerated
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.TRANS_NO
     *
     * @return the value of tbl_trans_log.TRANS_NO
     *
     * @mbggenerated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.TRANS_NO
     *
     * @param transNo the value for tbl_trans_log.TRANS_NO
     *
     * @mbggenerated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.TRANS_DT
     *
     * @return the value of tbl_trans_log.TRANS_DT
     *
     * @mbggenerated
     */
    public String getTransDt() {
        return transDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.TRANS_DT
     *
     * @param transDt the value for tbl_trans_log.TRANS_DT
     *
     * @mbggenerated
     */
    public void setTransDt(String transDt) {
        this.transDt = transDt == null ? null : transDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.TRANS_TM
     *
     * @return the value of tbl_trans_log.TRANS_TM
     *
     * @mbggenerated
     */
    public String getTransTm() {
        return transTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.TRANS_TM
     *
     * @param transTm the value for tbl_trans_log.TRANS_TM
     *
     * @mbggenerated
     */
    public void setTransTm(String transTm) {
        this.transTm = transTm == null ? null : transTm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.EVENT
     *
     * @return the value of tbl_trans_log.EVENT
     *
     * @mbggenerated
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.EVENT
     *
     * @param event the value for tbl_trans_log.EVENT
     *
     * @mbggenerated
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.ORDER_NO
     *
     * @return the value of tbl_trans_log.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.ORDER_NO
     *
     * @param orderNo the value for tbl_trans_log.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.PROD_CD
     *
     * @return the value of tbl_trans_log.PROD_CD
     *
     * @mbggenerated
     */
    public String getProdCd() {
        return prodCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.PROD_CD
     *
     * @param prodCd the value for tbl_trans_log.PROD_CD
     *
     * @mbggenerated
     */
    public void setProdCd(String prodCd) {
        this.prodCd = prodCd == null ? null : prodCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.OPERATOR_NM
     *
     * @return the value of tbl_trans_log.OPERATOR_NM
     *
     * @mbggenerated
     */
    public String getOperatorNm() {
        return operatorNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.OPERATOR_NM
     *
     * @param operatorNm the value for tbl_trans_log.OPERATOR_NM
     *
     * @mbggenerated
     */
    public void setOperatorNm(String operatorNm) {
        this.operatorNm = operatorNm == null ? null : operatorNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_trans_log.OPERATOR_ID
     *
     * @return the value of tbl_trans_log.OPERATOR_ID
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_trans_log.OPERATOR_ID
     *
     * @param operatorId the value for tbl_trans_log.OPERATOR_ID
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_trans_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", transNo=").append(transNo);
        sb.append(", transDt=").append(transDt);
        sb.append(", transTm=").append(transTm);
        sb.append(", event=").append(event);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", prodCd=").append(prodCd);
        sb.append(", operatorNm=").append(operatorNm);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}