server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称    集群版
  #    hostname: localhost  # eureka 服务端的实列名称   单机版
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  单机版
      defaultZone: http://eureka7002.com:7002/eureka/   # 集群版，指向 7002地址
